# -*- coding: utf-8 -*-
"""00_helloworld.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17rM0I6tCSNAv3bwl7R-yf_UTfJDJCUI-
"""

#Este simbolo se utiliza para comentar el codigo.
print("Hola grupo 230 de la carrera tecnica de programcion")
# como consultar el tipo de dato
print( type("soy un dato str")) #tipo ´str´
print(type(5)) # tipo ´int´
print(type(1.5)) # tipo ´float´
print(type(3+1j)) # tipo ´complex´
print(type(True)) # tipo bool
print(type("mi cadena de texto")) # tipo ´NoneType´